### ISSUE TITLE
calculateCompletion / overlapping scope of variables?

### ISSUE THREAD

**Issue by exff** [adaptlearning/adapt-contrib-pageLevelProgress#133]
Using _frame work_ 5.18.6 with _AT_ 0.10.5 and _adapt-contrib-pageLevelProgress-5.3.0_ on an older freshly imported course the progress level indication seemed to be completely messed up.

So I had to start some more extensive trouble-shooting. There may be some error in the code of _completionCalculations.js_ with regard to the function _calculateCompletion(contentObjectModel)_ and its recursive call in line 62.

I think a problem arises as for instance _completion.nonAssessmentTotal_ shares the same name

in line 34: _completion.nonAssessmentTotal = nonAssessmentComponents.length;_; and 
in line 65: _completion.nonAssessmentTotal += completionObject.nonAssessmentTotal;_

In line 65 a sum is calculated. However this sum is always reset when line 34 is calculated during the recursive call of the function.

I was able to see that by using console.log quite a bit in conjunction with a newly created simple dummy course. The same is true for the other related variables.

After basically correcting this error I got correct progress level indications on my course again.

However, after renaming the variables I had to adapt the initialization and _calculatePercentageComplete_ accordingly, as well.

Why this error did not pop-up in my older (pre 5 framework) version, I do not understand at this moment, as the code remained more or less unchanged since then.

Kind regards,
Wolfgang

**Comment by chris-steele** [comment]
Hi @exff would you mind posting the solution that you have (or branch off v5.3.0, amend with your solution and raise a PR)?

**Comment by oliverfoster** [comment]
Fixed in https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/149
