### ISSUE TITLE
pageLevelProgressEnd aria-label isn't used

### ISSUE THREAD

**Issue by kirsty-hames** [adaptlearning/adapt-contrib-pageLevelProgress#169]
### Subject of the issue
I can't see that `pageLevelProgressEnd` `aria-label` is used by the plugin. When I search for this it only returns the README and schema files. Was this removed at some point (I couldn't see anything in the blame history) or has this just been overlooked and never utilised?

### Expected behaviour
As per the `aria-label`, _"You have reached the end of the list of page sections"_, I'd expect this to read when you reach the bottom of the drawer.

**Comment by oliverfoster** [comment]
It was added here:
https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/commit/e4a0da4fc679ebe0e13c5a99e51b5279aecf14f0

I removed it here:
https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/107/files#diff-05054ebba911a0e314245b01f205b2ae340019dd7e04e74de5a928337d83b8ae

But seemingly forgot to remove the pageLevelProgressEnd aria label

**Comment by kirsty-hames** [comment]
Thanks for confirming @oliverfoster. I can't see we've implemented any end labels for other drawer functionality (e.g. resources) so is this fine to remove?

**Comment by oliverfoster** [comment]
Yup
