### ISSUE TITLE
_showAtCourseLevel: Add CSS classes

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-pageLevelProgress#176]
### Subject of the enhancement
When using `_showAtCourseLevel: true`, it would be helpful to have a class like `is-selected` that indicates which item in the PLP drawer is the current item (content object or menu).

In the following screenshot, it's difficult to tell that the user is currently in the "Adapt components" topic. Ideally, we would be able to style that button differently.

<img src="https://user-images.githubusercontent.com/898168/231796850-f6416238-6e4f-4d11-958a-bf187e18f829.jpg" width="250">

It may also be useful to have a class added to the `.pagelevelprogress` element that indicates if course level is being used (ex. `.is-course-level`).

**Comment by oliverfoster** [comment]
Yes to both.
