### ISSUE TITLE
Duplicates in the Page Level Progress Menu when using submenus

### ISSUE THREAD

**Issue by ludaus** [adaptlearning/adapt-contrib-pageLevelProgress#213]
### Duplicates within the Page Level Progress (PLP) menu
When using submenus in Adapt Authoring Tool, and then activating the setting "Display all content objects and the current page components" in PLP, the pages in the submenus appear twice in the PLP-menu.

### Your environment
* AT version 0.11.2
* Framework version 5.36.2
* Theme Vanilla 9.15.3 with some CSS added to change som typography and colors.
* Browser used: Chrome version 122.0.6261.129 
* Both on my Mac and my Windows computer. Mac OS Sonoma 14.3.1 and/or Windows 10.

### Steps to reproduce
Create submenus in a course (I call them chapters in the screenshot) , add pages to the submenus, and activate the "Display all content objects and the current page components" in the PLP settings.

### Expected behaviour
The pages in the submenus should show up only once in the PLP-menu.

### Actual behaviour
The pages in the submenus show up twice in the PLP-menu.

### Screenshots (if you can)
![PageLevelProgress-problem](https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/assets/21098681/fc7e8426-2a3b-40bf-9ff1-8d4035a2c771)

**Comment by joe-allen-89** [comment]
This is a duplicate issue and has been addressed in this pr https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/pull/212
