### ISSUE TITLE
Add option to show course progress on PLP nav button

### ISSUE THREAD

**Issue by swashbuck** [adaptlearning/adapt-contrib-pageLevelProgress#226]
### Subject of the enhancement
It would be a useful addition to be able to show the **course progress** on the nav bar _instead_ of the **current page's progress**. This is a customization we have made for clients in the past and present.

### Screenshot
<img width="439" alt="course-progress" src="https://github.com/adaptlearning/adapt-contrib-pageLevelProgress/assets/898168/2d8a8842-37ba-43e4-86bf-f307f6ea2b73">

**Comment by joe-replin** [comment]
Thanks for adding this in. With the previous addition of `"_showAtCourseLevel"`, we now have a nav bar that shows the page progress while the drawer displays progress of the entire course. This has led to some confusion and was alleviated by changing the navigational bar progress to increment on overall course level progress.
