### ISSUE TITLE
Incompatibility with adapt-contrib-blockslider

### ISSUE THREAD

**Issue by kzfabi** [adaptlearning/adapt-contrib-pageLevelProgress#53]
If I click on any of the menu options while using the blockslider extension, it doesn't show the corresponding slide, instead, it stays on the one your are currently viewing.

**Comment by moloko** [comment]
I think this issue is more likely to lie with adapt-contrib-blockslider - could you log a ticket there instead? If it does turn out to be an issue with PLP, the maintainer of blockslider will log a ticket here with detail as to what needs changing.

**Comment by moloko** [comment]
issue has been logged on https://github.com/LearningPool/adapt-contrib-blockslider/issues/3

closing this as for the moment there's no indication there's a problem with PLP itself.

**Comment by kzfabi** [comment]
ok, thanks!
