### ISSUE TITLE
completion calculation issue

### ISSUE THREAD

**Issue by chris-steele** [adaptlearning/adapt-contrib-pageLevelProgress#63]
A recent project has highlighted a problem with the way completion is calculated, resulting in PageLevelProgressNavigationView not rendering 100%.

Scenario: page has a subset of its components enabled for PLP. All components in this subset are completed. When other (non-optional) components remain incomplete the page remains incomplete. Because completionCalculations uses page completion in its calculation, PageLevelProgressNavigationView therefore does not render 100%.

**Comment by oliverfoster** [comment]
This is as intended. The non-optionals should be optional if they are not required for page / course completion

**Comment by chris-steele** [comment]
Thanks for the quick reply Ollie. I've got two developers who were completely unaware of that requirement. Oh, and me!

**Comment by oliverfoster** [comment]
Sorry, it was one of the last-minute design+implementation things that went in before the release of v2. I'm sure there are lots of people we should tell.

**Comment by chris-steele** [comment]
No probs, bound to be a few niggles of this sort. Just very relieved to have got a solution. This will go down better with the PM xD

**Comment by oliverfoster** [comment]
Sorry, just added a bit more to the comment above.
